refactor: use molecule partial load to calculate inputs len
cryptape/ckb-typed-message-poc pull request #19
Opened 2023-11-30 10:42 UTC by quake

The molecule table is serialized into 2 parts: [the header and the body](https://github.com/nervosnetwork/molecule/blob/master/docs/encoding_spec.md#memory-layout) , we can easily calculate the length of a specific field from the offsets, so that we can call syscall only once to calculate the number of inputs.

2023-11-30 11:31 UTC, XuJiandong requested changes

2023-11-30 11:31 UTC, XuJiandong commented on ckb-typed-message/src/lib.rs
> +    Ok((outputs_offset as usize - inputs_offset as usize - NUMBER_SIZE) / CellInput::TOTAL_SIZE)
Check `(outputs_offset - inputs_offset - NUMBER_SIZE) % CellInput::TOTAL_SIZE == 0`

2023-11-30 11:47 UTC, quake commented on ckb-typed-message/src/lib.rs
> +    let _ = load_transaction(&mut offsets, 28);
other errors like IndexOutOfBound / ItemMissing error won't happen in `load_transaction` syscall, we can ignore them safely.

2023-12-01 08:32 UTC, XuJiandong commented on ckb-typed-message/src/lib.rs
> +    let _ = load_transaction(&mut offsets, 28);
There are some other errors. And in the future, we might add more error code.

2023-12-03 23:51 UTC, quake commented on ckb-typed-message/src/lib.rs
> +    let _ = load_transaction(&mut offsets, 28);
updated, please review again, thanks.

2023-12-04 01:23 UTC, XuJiandong approved these changes

2023-12-04 01:23 UTC, merged